### ISSUE TITLE
Cannot read property 'inputVals ' of undefined

### ISSUE THREAD

**Issue by davidrhoderick** [imranhsayed/frontity-contact-form-7#31]
When using this package with Frontity 1.9.0 and a WYSIWYG field from ACF Pro, I get the following error:

```
TypeError: Cannot read property 'inputVals' of undefined
      at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/index.js:32:79)
      at Object.args [as addHiddenInputs] (webpack-internal:///./node_modules/@frontity/connect/src/create-store.js:5:1702)
      at HiddenInputs (webpack-internal:///./node_modules/frontity-contact-form-7/src/components/HiddenInput.js:15:261)
      at runAsReaction (webpack-internal:///./node_modules/@frontity/connect/src/reactionRunner.js:16:45)
      at reaction (webpack-internal:///./node_modules/@frontity/connect/src/observer.js:7:131)
      at props (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:21:16)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:397:2319)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:396:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:1199)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:55)
```
It was working on one of my machines installed from NPM version 0.1.4 but on another machine, I had to upgrade to get it working without using the deprecated `process` call.

**Comment by dejangeorgiev** [comment]
> When using this package with Frontity 1.9.0 and a WYSIWYG field from ACF Pro, I get the following error:
> 
> ```
> TypeError: Cannot read property 'inputVals' of undefined
>       at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/index.js:32:79)
>       at Object.args [as addHiddenInputs] (webpack-internal:///./node_modules/@frontity/connect/src/create-store.js:5:1702)
>       at HiddenInputs (webpack-internal:///./node_modules/frontity-contact-form-7/src/components/HiddenInput.js:15:261)
>       at runAsReaction (webpack-internal:///./node_modules/@frontity/connect/src/reactionRunner.js:16:45)
>       at reaction (webpack-internal:///./node_modules/@frontity/connect/src/observer.js:7:131)
>       at props (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:21:16)
>       at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:397:2319)
>       at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:396:122)
>       at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:1199)
>       at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:55)
> ```
> 
> It was working on one of my machines installed from NPM version 0.1.4 but on another machine, I had to upgrade to get it working without using the deprecated `process` call.

Same Issue here.

**Comment by warudin** [comment]
Same problem here, however I don't have an ACF WYSIWYG field as mentioned in the OP:

`TypeError: Cannot read property 'inputVals' of undefined
      at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/index.js:32:79)
      at Object.eval [as addHiddenInputs] (webpack-internal:///./node_modules/@frontity/connect/src/create-store.js:5:1702)
      at HiddenInputs (webpack-internal:///./node_modules/frontity-contact-form-7/src/components/HiddenInput.js:15:261)
      at runAsReaction (webpack-internal:///./node_modules/@frontity/connect/src/reactionRunner.js:16:45)
      at reaction (webpack-internal:///./node_modules/@frontity/connect/src/observer.js:7:131)
      at eval (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:21:16)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:397:2319)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:396:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:1199)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:55)`

**Comment by anantajitjg** [comment]
I thinks this error is due to an update in cf7 v5.2. I have submitted a PR #32

**Comment by dejangeorgiev** [comment]
> I think this error is due to an update in cf7 v5.2. I have submitted a PR #32

Great! Thank you @anantajitjg 
Do you know when it will be available on npm?

**Comment by anantajitjg** [comment]
> Do you know when it will be available on npm?

Sorry! No.

You can install frontity-contact-form-7 package locally(with PR changes) to test if the issue is solved. May be this link will be helpful for you: https://docs.frontity.org/guides/install-a-new-package#local-packages. You can use the package from [here](https://github.com/anantajitjg/frontity-contact-form-7/tree/fix/2/packages/contact-form-7) for your local package.

Also, you can [downgrade the cf7](https://downloads.wordpress.org/plugin/contact-form-7.5.1.9.zip) plugin and test if the issue is solved for now. Hope it helps!

**Comment by luisherranz** [comment]
Thanks @anantajitjg I have merged the PR. I don't have access to publish the npm package so that has to be done by @imranhsayed.

**Comment by anantajitjg** [comment]
Thanks @luisherranz for merging the PR. I hope the new version will be released soon by @imranhsayed  🙂 🤞

**Comment by kilinkis** [comment]
I tried the solution that @anantajitjg said of installing locally, and that fixed it for me :)

**Comment by warudin** [comment]
For me as well. Hopefully it will be updated on NPM soon.

**Comment by warudin** [comment]
The update is available on NPM now
