### ISSUE TITLE
Form not responding

### ISSUE THREAD

**Issue by jeffceriello** [imranhsayed/frontity-contact-form-7#41]
Hi there,

I have added and displayed the Contact Form 7 form in a Frontity application correctly but when I submit it I don't get any validation error nor the form sends. I see the text "Processing..." and nothing else after that.

Is there a bug or have I misconfigured the form somehow?

Here is a link that shows the issue

https://wwt-evildonkey.vercel.app/connect/

Thanks,
Jeff

**Comment by luisherranz** [comment]
Hey @jeffcerielo, could you please try this one instead? https://www.npmjs.com/package/@aamodtgroup/frontity-contact-form-7

If that one works, we'll ask the owner to do a PR to this repository with the fix 🙂

**Comment by jeffceriello** [comment]
Hey @luisherranz, thank you so much! I've just tested it and it works.

Thank you!!

**Comment by jeffceriello** [comment]
Hi @luisherranz 

I've just had to delete the node_modules folder + package-lock.json file and reinstall all modules but when I now run `npx frontity dev` I get the following error, which I believe is linked to this module

```
TypeError: Cannot assign to read only property 'name' of function 'props=>{// Dummy setState to update the component.
const[,setState]=Object(react__WEBPACK_IMPORTED_MODULE_1__["...<omitted>...}}'
    at eval (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:71)
    at Array.forEach (<anonymous>)
    at connect (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:40)
    at eval (webpack-internal:///./node_modules/@aamodtgroup/frontity-contact-form-7/src/processors/cf7HiddenInputs.js:5:568)
    at Module../node_modules/@aamodtgroup/frontity-contact-form-7/src/processors/cf7HiddenInputs.js (/Users/jeffceriello/Sites/frontity/wwt/build/server.js:283:1)
    at __webpack_require__ (/Users/jeffceriello/Sites/frontity/wwt/build/server.js:27:30)
    at eval (webpack-internal:///./node_modules/@aamodtgroup/frontity-contact-form-7/src/index.js:9:85)
    at Module../node_modules/@aamodtgroup/frontity-contact-form-7/src/index.js (/Users/jeffceriello/Sites/frontity/wwt/build/server.js:259:1)
    at __webpack_require__ (/Users/jeffceriello/Sites/frontity/wwt/build/server.js:27:30)
    at eval (webpack-internal:///./build/bundling/entry-points/server.ts:7:104)
```

Do you know why that would happen?

**Comment by luisherranz** [comment]
Is it related to this issue?

**Comment by jeffceriello** [comment]
By reading through the error I see it goes into `/node_modules/@aamodtgroup/frontity-contact-form-7/`, I believe it is related to this issue? I apologise if not.

**Comment by luisherranz** [comment]
Then please report it here with a CodeSandbox and the steps to reproduce the problem: https://github.com/aamodtgroup/frontity-contact-form-7.

Thanks!
