### ISSUE TITLE
Frontity connect() creates issue with latest frontity version

### ISSUE THREAD

**Issue by DonKoko** [imranhsayed/frontity-contact-form-7#46]
I have just updated my packages to the latest frontity version and have faced an issue related to the `frontity-contact-form-7` package.
Everything installs properly but on page load I get the following error:

```sh
TypeError: Cannot assign to read only property 'name' of function 'props=>{// Dummy setState to update the component.
const[,setState]=Object(react__WEBPACK_IMPORTED_MODULE_1__["...<omitted>...}}'
    at eval (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:71)
    at Array.forEach (<anonymous>)
    at connect (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:40)
    at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/processors/cf7HiddenInputs.js:5:568)
    at Module../node_modules/frontity-contact-form-7/src/processors/cf7HiddenInputs.js (/Users/donkoko/devs/JS/kh-frontity-theme/build/server.js:3236:1)
    at __webpack_require__ (/Users/donkoko/devs/JS/kh-frontity-theme/build/server.js:27:30)
    at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/index.js:9:85)
    at Module../node_modules/frontity-contact-form-7/src/index.js (/Users/donkoko/devs/JS/kh-frontity-theme/build/server.js:3212:1)
    at __webpack_require__ (/Users/donkoko/devs/JS/kh-frontity-theme/build/server.js:27:30)
    at eval (webpack-internal:///./build/bundling/entry-points/server.ts:9:91)
 ```

I tried removing the `connect()` from `cf7HiddenInputs` & `cf7Span` processors and that solved the issue.

Here is the frontity info:
```
## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 84.33 MB / 8.00 GB
 - Shell: 5.1.4 - /usr/local/bin/bash
## Binaries:
 - Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
 - npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
## Browsers:
 - Chrome: 90.0.4430.212
 - Edge: 90.0.818.62
 - Firefox: 70.0.1
 - Safari: 14.0.3
## npmPackages:
 - @frontity/core: ^1.14.0 => 1.14.0 
 - @frontity/head-tags: ^1.1.1 => 1.1.1 
 - @frontity/html2react: ^1.7.0 => 1.7.0 
 - @frontity/koenighaus-theme: ./packages/koenighaus-theme => 1.4.2 
 - @frontity/tiny-router: ^1.4.2 => 1.4.2 
 - @frontity/wp-source: ^1.11.4 => 1.11.4 
 - @hookform/error-message: 0.0.5 => 0.0.5 
 - axios: ^0.21.1 => 0.21.1 
 - frontity: ^1.15.0 => 1.15.0 
 - frontity-contact-form-7: ^0.1.7 => 0.1.7 
 - js-cookie: ^2.2.1 => 2.2.1 
 - kh-calculator: file:packages/kh-calculator => 0.0.1 
 - libphonenumber-js: ^1.9.18 => 1.9.18 
 - libphonenumber-js-core:  1.0.0 
 - libphonenumber-js-max:  1.0.0 
 - libphonenumber-js-min:  1.0.0 
 - libphonenumber-js-mobile:  1.0.0 
 - react-hook-form: ^6.15.7 => 6.15.7 
 - react-modal: ^3.13.1 => 3.13.1 
 - react-scroll: ^1.8.2 => 1.8.2 
 - react-select: ^3.2.0 => 3.2.0 
 - react-spring: ^8.0.27 => 8.0.27 
 - woocommerce-shop: file:packages/woocommerce-shop => 1.0.0 
 ```

Does somebody else have the same problem? I would love to help to get to the bottom of it.

**Comment by bayuslari** [comment]
@DonKoko hey mate, I have exactly same issue here. 
Would you share the fixes?

**Comment by DonKoko** [comment]
hey @bayuslari. Did you try the latest version. After updating frontity core and the cf7 package, the issue was solved for me.
