### ISSUE TITLE
TypeError in plugin

### ISSUE THREAD

**Issue by LowRadiance** [imranhsayed/frontity-contact-form-7#50]
I'm doing my first steps in Frontity. Using that plugin here for a contact form 7 gives the following output:
`TypeError: Cannot assign to read only property 'name' of function 'props=>{// Dummy setState to update the component.
const[,setState]=Object(react__WEBPACK_IMPORTED_MODULE_1__["...<omitted>...}}'
    at Object.keys.forEach.key (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:71)
    at Array.forEach (<anonymous>)
    at connect (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:40)
    at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/processors/cf7HiddenInputs.js:5:568)
    at Module../node_modules/frontity-contact-form-7/src/processors/cf7HiddenInputs.js (/home/oskar/ProgrammersBlog/build/server.js:2845:1)
    at __webpack_require__ (/home/oskar/ProgrammersBlog/build/server.js:27:30)
    at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/index.js:9:85)
    at Module../node_modules/frontity-contact-form-7/src/index.js (/home/oskar/ProgrammersBlog/build/server.js:2821:1)
    at __webpack_require__ (/home/oskar/ProgrammersBlog/build/server.js:27:30)
    at eval (webpack-internal:///./build/bundling/entry-points/server.ts:8:91)`

I did a clean installation from scratch today but the issue persists. I also changed the contact form in my blog, but still the same issue.

**Comment by kasperaamodt** [comment]
Look at this issue #48
