### ISSUE TITLE
Getting a strange error and entire site breaks after adding package

### ISSUE THREAD

**Issue by nigeymc** [imranhsayed/frontity-contact-form-7#56]
After installing the package and adding it to frontity.settings.js my site breaks and I get the following error...

```TypeError: Cannot assign to read only property 'name' of function 'props=>{// Dummy setState to update the component.
const[,setState]=Object(react__WEBPACK_IMPORTED_MODULE_1__["...<omitted>...}}'
    at eval (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:71)
    at Array.forEach (<anonymous>)
    at connect (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:40)
    at eval (webpack-internal:///./node_modules/frontity-contact-form-7/src/processors/cf7HiddenInputs.js:5:568)
    at Module../node_modules/frontity-contact-form-7/src/processors/cf7HiddenInputs.js ...

**Comment by davemoz** [comment]
FWIW, I'm getting the same error, but also an additional line before what OP has above:

```
TypeError: Cannot assign to read only property 'name' of function 'props=>{// Dummy setState to update the component.
const[,setState]=Object(react__WEBPACK_IMPORTED_MODULE_1__["...<omitted>...}}'
    at eval (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:91:71)`
...
```

**Comment by kasperaamodt** [comment]
Look at this issue #48
